language: android
android:
 components:
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository

jdk: oraclejdk8

before_install:
- yes | sdkmanager "platforms;android-27"

jobs:
  include:
  - stage: build
    script: ./gradlew build
  - stage: test
    script: ./gradlew test
